server:
  port: 8081
spring:
  application:
    name: robin-tools-code-generator
  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:/templates
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    suffix: .html
  mvc:
    static-path-pattern: /static/**
  app:
    name: '@project.artifactId@'
    version: '@project.version@'
logging:
  level:
    com.baomidou: debug